export const socialLinks = {
  instagram: "https://www.instagram.com/dukeimpactinvesting/",
  linkedin: "https://www.linkedin.com/company/diig/",
  email: "diigbd@gmail.com",
};

export const leadership = {
  partners: [
    { name: "Danielle Park", year: 2027 },
    { name: "Andy Li", year: 2026 },
    { name: "Alayna Binder", year: 2026 },
    { name: "Sreya Gnanavel", year: 2026 },
  ],
  directors: [
    { name: "Amy Liu", division: "Data" },
    { name: "Rocky Zhang", division: "Data" },
    { name: "Gabriela Nicolaievsky", division: "Consulting" },
    { name: "Shiv Batra", division: "Consulting" },
    { name: "Ella Veysel", division: "Business Development" },
    { name: "Sami Moudarres", division: "Business Development" },
    { name: "Jack Hirsh", division: "Investment" },
    { name: "Rendon Kuykendall", division: "Investment" },
    { name: "Suhaib Mansour", division: "Education" },
    { name: "Jimmy Helferty", division: "Education" },
    { name: "Anthony Lotruglio", division: "Treasurer" },
  ],
};

export const roster = {
  bd: [
    {
      name: "Reeha Rahman",
      role: "Analyst",
      year: 2029,
      majors: "Neuroscience",
      linkedin: "https://www.linkedin.com/in/reeharahman",
      subdivision: "",
    },
    {
      name: "Ella Veysel",
      role: "Director",
      year: 2026,
      majors: "Risk, Data, and Financial Engineering",
      linkedin: "https://www.linkedin.com/in/ellaveysel",
      subdivision: "",
    },
    {
      name: "Sami Moudarres",
      role: "Director",
      year: 2028,
      majors: "Economics",
      linkedin: "https://www.linkedin.com/in/sami-moudarres-833977276",
      subdivision: "",
    },
    {
      name: "Penelope James",
      role: "Project Manager",
      year: 2026,
      majors: "Economics",
      linkedin: "https://www.linkedin.com/in/penelope-james-540012292",
      subdivision: "Marketing",
    },
    {
      name: "Rachel Talcoff",
      role: "Project Manager",
      year: 2027,
      majors: "Economics & Politial Science",
      linkedin: "https://www.linkedin.com/in/rachel-talcoff",
      subdivision: "Marketing",
    },
    {
      name: "Sean Clairine",
      role: "Analyst",
      year: 2028,
      majors: "Political Science",
      linkedin: "https://www.linkedin.com/in/seanclairine",
      subdivision: "Growth",
    },
    {
      name: "Mia Jantac",
      role: "Analyst",
      year: 2028,
      majors: "Neuroscience & Economics",
      linkedin: "https://www.linkedin.com/in/mia-jantac-294ba22b2",
      subdivision: "Growth",
    },
    {
      name: "Ceane Corbett",
      role: "Analyst",
      year: 2028,
      majors: "Economics & Markets and Managment",
      linkedin: "https://www.linkedin.com/in/ceane-corbett-b4bb91286",
      subdivision: "Growth",
    },
    {
      name: "Mika'il Naqvi",
      role: "Analyst",
      year: 2029,
      majors: "History & Economics",
      linkedin: "https://www.linkedin.com/in/mikailnaqvi78626",
      subdivision: "Growth",
    },
    {
      name: "Ahana Kotibhaskar",
      role: "Analyst",
      year: 2029,
      majors: "Economics",
      linkedin: "https://www.linkedin.com/in/ahana-kotibhaskar-3619b3283",
      subdivision: "Growth",
    },
    {
      name: "Jacob Brill",
      role: "Analyst",
      year: 2028,
      majors: "Economics",
      linkedin: "https://www.linkedin.com/in/jacobbrill",
      subdivision: "Growth",
    },
    {
      name: "Nathan Schwartz",
      role: "Analyst",
      year: 2029,
      majors: "Economics & Mathematics",
      linkedin: "https://www.linkedin.com/in/nathan-schwartz29",
      subdivision: "Growth",
    },
    {
      name: "Julia Surzykiewicz",
      role: "Analyst",
      year: 2029,
      majors: "Neuroscience & Economics",
      linkedin: "https://www.linkedin.com/in/julia-surzykiewicz-54a960296",
      subdivision: "Growth",
    },
    {
      name: "Mia Liu",
      role: "Analyst",
      year: 2029,
      majors: "Economics & Computer Science",
      linkedin: "https://www.linkedin.com/in/miayliu",
      subdivision: "Growth",
    },
    {
      name: "Carina Kehoe",
      role: "Analyst",
      year: 2027,
      majors: "Economics & Politial Science",
      linkedin: "https://www.linkedin.com/in/carinakehoe",
      subdivision: "Marketing",
    },
    {
      name: "Nilay Ghodasara",
      role: "Analyst",
      year: 2027,
      majors: "Economics & Public Policy",
      linkedin: "https://www.linkedin.com/in/nilayghodasara",
      subdivision: "Marketing",
    },
    {
      name: "Kevin Ma",
      role: "Analyst",
      year: 2028,
      majors: "Economics & Cinematic Arts",
      linkedin: "https://www.linkedin.com/in/kevin-ma-6a84792a2",
      subdivision: "Marketing",
    },
    {
      name: "Layelle Abou-Ezzi",
      role: "Analyst",
      year: 2028,
      majors: "Public Policy & Neuroscience",
      linkedin: "https://www.linkedin.com/in/layelleabouezzi",
      subdivision: "Marketing",
    },
    {
      name: "Hannah Shin",
      role: "Analyst",
      year: 2029,
      majors: "Economics",
      linkedin: "https://www.linkedin.com/in/hannah-shin-96b49832b",
      subdivision: "Marketing",
    },
    {
      name: "Ethan Jiang",
      role: "Analyst",
      year: 2029,
      majors: "Economics",
      linkedin: "https://www.linkedin.com/in/ethannjiang",
      subdivision: "Marketing",
    },
    {
      name: "Ally Reich",
      role: "Analyst",
      year: 2028,
      majors: "Psychology & Markets and Management",
      linkedin: "https://www.linkedin.com/in/ally-reich-84b656382",
      subdivision: "Marketing",
    },
    {
      name: "Cecily Burns",
      role: "Analyst",
      year: 2029,
      majors: "Economics & Public Policy",
      linkedin: "https://www.linkedin.com/in/cecily-burns-152b41380",
      subdivision: "Marketing",
    },
    {
      name: "Annabelle Wei",
      role: "Analyst",
      year: 2029,
      majors: "Psychology & Economics",
      linkedin: "https://www.linkedin.com/in/annabelle-wei-a0b059337",
      subdivision: "Marketing",
    },
    {
      name: "Allison Hu",
      role: "Analyst",
      year: 2029,
      majors: "Biology & Computer science",
      linkedin: "https://www.linkedin.com/in/allison-hu-",
      subdivision: "Marketing",
    },
    {
      name: "Claire Peng",
      role: "Analyst",
      year: 2029,
      majors: "Economics & Computer Science",
      linkedin: "https://www.linkedin.com/in/claire-peng-95b1a4378",
      subdivision: "Open",
    },
    {
      name: "Charlyn Chu",
      role: "PREV GROWTH PM",
      year: 2028,
      majors: "Statistics & Economics",
      linkedin: "https://www.linkedin.com/in/charlynchu",
      subdivision: "Growth",
    },
  ],
  consulting: [
    {
      name: "Harry Clark",
      role: "Analsyt",
      year: 2029,
      majors: "Economics & History",
      linkedin: "https://www.linkedin.com/in/harry-clark1717",
      subdivision: "",
    },
    {
      name: "Jacob Kim",
      role: "Analyst",
      year: 2029,
      majors: "Economics",
      linkedin: "https://www.linkedin.com/in/jacobtkim",
      subdivision: "",
    },
    {
      name: "Diego Keller",
      role: "Analyst",
      year: 2028,
      majors: "Financial Economics & Public Policy",
      linkedin: "https://www.linkedin.com/in/diego-keller-570a95228",
      subdivision: "",
    },
    {
      name: "Karthi Ramiah",
      role: "PM",
      year: 2027,
      majors: "Economics & Statistics",
      linkedin: "https://www.linkedin.com/in/karthi-ramiah",
      subdivision: "",
    },
    {
      name: "Antonio Wu Zen",
      role: "Analyst",
      year: 2029,
      majors: "Economics & Computer Science",
      linkedin: "https://www.linkedin.com/in/antonio-wu-zen",
      subdivision: "",
    },
    {
      name: "Shreya Nallamothu",
      role: "Analyst",
      year: 2029,
      majors: "Computer Science & Public Policy",
      linkedin: "https://www.linkedin.com/in/shreyanallamothu",
      subdivision: "",
    },
    {
      name: "Anthony Benbenek",
      role: "PM",
      year: 2028,
      majors: "Political Science & Economics",
      linkedin: "https://www.linkedin.com/in/anthony-a-benbenek-8b5098327",
      subdivision: "",
    },
    {
      name: "Claire Chen",
      role: "Analyst",
      year: 2028,
      majors: "Economics & English",
      linkedin: "https://www.linkedin.com/in/claire-chen-1b5277327",
      subdivision: "",
    },
    {
      name: "Brianna yang",
      role: "Analyst",
      year: 2028,
      majors: "Public Policy & Computer Science",
      linkedin: "https://www.linkedin.com/in/brianna-c-yang",
      subdivision: "",
    },
    {
      name: "Eric Min",
      role: "PM",
      year: 2027,
      majors: "Economics & Statistics",
      linkedin: "https://www.linkedin.com/in/jaehong-min",
      subdivision: "",
    },
    {
      name: "Aditi Vikram",
      role: "Analyst",
      year: 2029,
      majors: "Economics & Environmental Science and Policy",
      linkedin: "https://www.linkedin.com/in/aditi-vikram-duke2029",
      subdivision: "",
    },
    {
      name: "May Lou",
      role: "Analyst",
      year: 2029,
      majors: "Public Policy & Statistics",
      linkedin: "https://www.linkedin.com/in/may-lou-12b5b1382",
      subdivision: "",
    },
    {
      name: "Madeleine Dean",
      role: "PM",
      year: 2026,
      majors: "Public Policy & Environmental Sciences and Policy",
      linkedin: "https://www.linkedin.com/in/madeleine-d-3b7b07204",
      subdivision: "",
    },
    {
      name: "Hayden Chang",
      role: "Analyst",
      year: 2029,
      majors: "Political Science",
      linkedin: "https://www.linkedin.com/in/haydenchang",
      subdivision: "",
    },
    {
      name: "Chloe Chun",
      role: "PM",
      year: 2028,
      majors: "Economics & Computational Media",
      linkedin: "https://www.linkedin.com/in/chloetchun",
      subdivision: "",
    },
    {
      name: "Raahi Soni",
      role: "Analyst",
      year: 2029,
      majors: "Economics & Statistics",
      linkedin: "https://www.linkedin.com/in/raahisoni",
      subdivision: "",
    },
    {
      name: "Juhee Grace Kim",
      role: "PM",
      year: 2029,
      majors: "Statistics & Philosophy",
      linkedin: "https://www.linkedin.com/in/juhee-kim-a7a47a34a",
      subdivision: "",
    },
    {
      name: "Owen Liu",
      role: "Analyst",
      year: 2028,
      majors: "Economics",
      linkedin: "https://www.linkedin.com/in/oliuowen",
      subdivision: "",
    },
    {
      name: "Carson Cattano",
      role: "Analyst",
      year: 2029,
      majors: "Economics & Philosophy",
      linkedin: "https://www.linkedin.com/in/carson-cattano-b80160241",
      subdivision: "",
    },
    {
      name: "Ella Bilu",
      role: "Analyst",
      year: 2029,
      majors: "Public Policy & Journalism and Media",
      linkedin: "https://www.linkedin.com/in/ella-bilu-a51643220",
      subdivision: "",
    },
    {
      name: "Ryan Hahm",
      role: "Analyst",
      year: 2029,
      majors: "Economics & Statisitcs",
      linkedin: "https://www.linkedin.com/in/ryan-hahm-duke",
      subdivision: "",
    },
    {
      name: "Sanjaay Babu",
      role: "Analyst",
      year: 2029,
      majors: "Economics & Philosophy",
      linkedin: "https://www.linkedin.com/in/sanjaay-babu-sg",
      subdivision: "",
    },
    {
      name: "Noa Bremen",
      role: "PM",
      year: 2028,
      majors: "Neuroscience & Economics",
      linkedin: "https://www.linkedin.com/in/noa-paige-bremen",
      subdivision: "",
    },
    {
      name: "Leah Perlman",
      role: "PM",
      year: 2026,
      majors: "Economics & English",
      linkedin: "https://www.linkedin.com/in/leah-perlman",
      subdivision: "",
    },
    {
      name: "Miriam Leah Ivanenko",
      role: "PM, DKU-Duke Liaison",
      year: 2027,
      majors: "Economics & Chinese",
      linkedin: "https://www.linkedin.com/in/miriam-leah-ivanenko",
      subdivision: "",
    },
    {
      name: "Kushal Hiremath",
      role: "Analyst",
      year: 2029,
      majors: "Economics & Psychology",
      linkedin: "https://www.linkedin.com/in/kushalhiremath14",
      subdivision: "",
    },
    {
      name: "Danial Hendi",
      role: "Analyst",
      year: 2028,
      majors: "Economics",
      linkedin: "https://www.linkedin.com/in/danialhendi",
      subdivision: "",
    },
    {
      name: "Chloe Tan",
      role: "Analyst",
      year: 2029,
      majors: "Economics & Psychology",
      linkedin: "https://www.linkedin.com/in/chloe-tan-547373216",
      subdivision: "",
    },
    {
      name: "Hipolito Gonzalez",
      role: "Analyst",
      year: 2029,
      majors: "Electrical and Computer Engineering",
      linkedin:
        "https://www.linkedin.com/in/hipolito-gonzalez-gerard-62353a323",
      subdivision: "",
    },
    {
      name: "Jose De Oteyza",
      role: "Analyst",
      year: 2028,
      majors: "Economics & Political Science",
      linkedin: "https://www.linkedin.com/in/jose-de-oteyza-4963242b4",
      subdivision: "",
    },
    {
      name: "Sawyer Karish",
      role: "Analyst",
      year: 2029,
      majors: "Biology & Evolutionary Anthropology",
      linkedin: "https://www.linkedin.com/in/sawyer-karish-9a6138382",
      subdivision: "",
    },
    {
      name: "Lu jia Lucia Liu Li",
      role: "Analyst",
      year: 2027,
      majors: "Computational Design & Social Policy",
      linkedin: "https://www.linkedin.com/in/lu-jia-liu-li",
      subdivision: "",
    },
    {
      name: "Kabir Chaudry",
      role: "Analyst",
      year: 2029,
      majors: "Economics & Computer Science",
      linkedin: "https://www.linkedin.com/in/kabir-chaudry",
      subdivision: "",
    },
    {
      name: "Selin Mutlu",
      role: "Analyst",
      year: 2029,
      majors: "Mathematics & Education",
      linkedin: "https://www.linkedin.com/in/selin-s-mutlu",
      subdivision: "",
    },
  ],
  data: [
    {
      name: "Amy Liu",
      role: "Co-Director",
      year: 2027,
      majors: "Computer Science & Statistics",
      linkedin: "https://www.linkedin.com/in/amyhliu27",
      subdivision: "",
    },
    {
      name: "Rocky Zhang",
      role: "Co-Director",
      year: 2027,
      majors: "Mathematics & Computer Science & Political Science",
      linkedin: "https://www.linkedin.com/in/lirockyzhang",
      subdivision: "",
    },
    {
      name: "Sahil Patel",
      role: "PM",
      year: 2027,
      majors: "Mathematics & Computer Science",
      linkedin: "https://www.linkedin.com/in/sahil-patel-4ab71320a",
      subdivision: "",
    },
    {
      name: "Aarsh Roongta",
      role: "PM",
      year: 2028,
      majors: "Computer Science & Statistics",
      linkedin: "https://www.linkedin.com/in/aarsh-roongta",
      subdivision: "",
    },
    {
      name: "Soham Jinsi",
      role: "PM",
      year: 2028,
      majors: "Mathematics & Computer Science",
      linkedin: "https://www.linkedin.com/in/soham-jinsi",
      subdivision: "",
    },
    {
      name: "Edward Song",
      role: "PM",
      year: 2028,
      majors: "Statistics & Economics",
      linkedin: "https://www.linkedin.com/in/edward-song-7627182b1",
      subdivision: "",
    },
    {
      name: "Amogh Manral",
      role: "PM",
      year: 2028,
      majors: "Computer Science & Statistics",
      linkedin: "https://www.linkedin.com/in/amogh-manral-688736248",
      subdivision: "",
    },
    {
      name: "David Li",
      role: "PM",
      year: 2028,
      majors: "Computer Science & Economics",
      linkedin: "https://www.linkedin.com/in/david-x-li",
      subdivision: "",
    },
    {
      name: "Yule Fu",
      role: "PM",
      year: 2027,
      majors: "Mathematics & Statistics",
      linkedin: "https://www.linkedin.com/in/yule-fu-1230ml",
      subdivision: "",
    },
    {
      name: "Beatrice Ghosn",
      role: "PM",
      year: 2027,
      majors: "Computer Science & Statistics",
      linkedin: "https://www.linkedin.com/in/beatrice-ghosn",
      subdivision: "",
    },
    {
      name: "Ian Le",
      role: "Operations",
      year: 2028,
      majors: "Computer Science & Statistics",
      linkedin: "https://www.linkedin.com/in/ian-le",
      subdivision: "",
    },
    {
      name: "Samya Chauhan",
      role: "Data Analyst",
      year: 2028,
      majors: "Computer Science & Finance",
      linkedin: "https://www.linkedin.com/in/samyachauhan",
      subdivision: "",
    },
    {
      name: "Liane Ma",
      role: "Data Analyst",
      year: 2027,
      majors: "Statistics",
      linkedin: "https://www.linkedin.com/in/lianema",
      subdivision: "",
    },
    {
      name: "Jacky Yang",
      role: "Data Analyst",
      year: 2029,
      majors: "Computer Science & Economics",
      linkedin: "https://www.linkedin.com/in/jacky-yang-duke",
      subdivision: "",
    },
    {
      name: "Rohith Kumar",
      role: "Data Analyst",
      year: 2029,
      majors: "Electrical and Computer Engineering & Computer Science",
      linkedin: "https://www.linkedin.com/in/rohith-kumar-911949249",
      subdivision: "",
    },
    {
      name: "Arihant Rajesh",
      role: "Data Analyst",
      year: 2029,
      majors: "Biomedical Engineering & Computer Science",
      linkedin: "https://www.linkedin.com/in/arihant-r-4360732ba",
      subdivision: "",
    },
    {
      name: "Parker Hayashi",
      role: "Data Analyst",
      year: 2029,
      majors: "Computer Science & Statistics",
      linkedin: "https://www.linkedin.com/in/parkerhayashi",
      subdivision: "",
    },
    {
      name: "Mahima Gyamlani",
      role: "Data Analyst",
      year: 2028,
      majors: "Computer Science & Statistics",
      linkedin: "https://www.linkedin.com/in/mahimagyamlani",
      subdivision: "",
    },
    {
      name: "Keith LoboPrabhu",
      role: "Data Analyst",
      year: 2029,
      majors: "Economics & Public Policy",
      linkedin: "https://www.linkedin.com/in/keithloboprabhu",
      subdivision: "",
    },
    {
      name: "Bella Raymond",
      role: "Data Analyst",
      year: 2028,
      majors: "Electrical and Computer Engineering",
      linkedin: "https://www.linkedin.com/in/isabelle-raymond-144390374",
      subdivision: "",
    },
    {
      name: "Ashley Park",
      role: "Data Analyst",
      year: 2028,
      majors: "Computer Science & Statistics",
      linkedin: "https://www.linkedin.com/in/ashleyebpark",
      subdivision: "",
    },
    {
      name: "James Wright",
      role: "Data Analyst",
      year: 2029,
      majors: "Computer Science & Mathematics",
      linkedin: "https://www.linkedin.com/in/james-wright-7798a4326",
      subdivision: "",
    },
    {
      name: "Sebastian Estrada",
      role: "Data Analyst",
      year: 2029,
      majors: "Electrical and Computer Engineering & Mathematics",
      linkedin: "https://www.linkedin.com/in/sebastian-estrada-9875ab307",
      subdivision: "",
    },
    {
      name: "Ashia Agarwal",
      role: "Data Analyst",
      year: 2029,
      majors: "Computer Science & Mathematics",
      linkedin: "https://www.linkedin.com/in/ashia-agarwal-35b93321a",
      subdivision: "",
    },
    {
      name: "Simon Stryszak",
      role: "Data Analyst",
      year: 2028,
      majors: "Biomedical Engineering & Economics",
      linkedin: "https://www.linkedin.com/in/simon-stryszak-51535b325",
      subdivision: "",
    },
    {
      name: "Amy Xu",
      role: "Data Analyst",
      year: 2027,
      majors: "Statistics",
      linkedin: "https://www.linkedin.com/in/amy-xu-924769291",
      subdivision: "",
    },
    {
      name: "Tally Coulter",
      role: "Data Analyst",
      year: 2027,
      majors: "Statistics",
      linkedin: "https://www.linkedin.com/in/natalie-coulterr",
      subdivision: "",
    },
    {
      name: "Manya Bhagat",
      role: "Data Analyst",
      year: 2028,
      majors: "Computer Science & Economics",
      linkedin: "https://www.linkedin.com/in/manya-bhagat",
      subdivision: "",
    },
    {
      name: "Rithika Saravanan",
      role: "Data Analyst",
      year: 2027,
      majors: "Computer Science & Statistics",
      linkedin: "https://www.linkedin.com/in/rithika-saravanan",
      subdivision: "",
    },
    {
      name: "Andy Sun",
      role: "Data Analyst",
      year: 2029,
      majors: "Computer Science & Statistics",
      linkedin: "https://www.linkedin.com/in/andy-sun-7b75a9266",
      subdivision: "",
    },
    {
      name: "Ian Prazak",
      role: "Data Analyst",
      year: 2029,
      majors: "Computer Science & Statistics",
      linkedin: "https://www.linkedin.com/in/ian-prazak-02303027a",
      subdivision: "",
    },
    {
      name: "Shreyan Singha",
      role: "Data Analyst",
      year: 2029,
      majors: "Economics & Statistics",
      linkedin: "https://www.linkedin.com/in/shreyan-singha",
      subdivision: "",
    },
    {
      name: "Aashiv Jain",
      role: "Data Analyst",
      year: 2029,
      majors: "Computer Science & Statistics",
      linkedin: "https://www.linkedin.com/in/aashiv-jain",
      subdivision: "",
    },
    {
      name: "Anusha Kamath",
      role: "Data Analyst",
      year: 2029,
      majors: "Statistics",
      linkedin: "https://www.linkedin.com/in/anusha-kamath-",
      subdivision: "",
    },
    {
      name: "Rachel Yu",
      role: "Data Analyst",
      year: 2028,
      majors: "Electrical and Computer Engineering & Computer Science",
      linkedin: "https://www.linkedin.com/in/rachelyu0624",
      subdivision: "",
    },
    {
      name: "Hanna Chee",
      role: "Data Analyst",
      year: 2029,
      majors: "Statistics",
      linkedin: "https://www.linkedin.com/in/hanna-chee-496461387",
      subdivision: "",
    },
    {
      name: "Ronit Dey",
      role: "Data Analyst",
      year: 2029,
      majors: "Computer Science",
      linkedin: "https://www.linkedin.com/in/ronit-dey-249818246",
      subdivision: "",
    },
    {
      name: "Echo Li",
      role: "Data Analyst",
      year: 2027,
      majors: "Computer Science & History",
      linkedin: "https://www.linkedin.com/in/echo-li-8b59b728b",
      subdivision: "",
    },
    {
      name: "Sophie Xu",
      role: "Data Analyst",
      year: 2027,
      majors: "Statistics",
      linkedin: "https://www.linkedin.com/in/sophie-xu-352240241",
      subdivision: "",
    },
    {
      name: "Anoushka Chaudhury",
      role: "Data Analyst",
      year: 2029,
      majors: "Computer Science & Statistics",
      linkedin: "https://www.linkedin.com/in/anoushka-chaudhury-540497313",
      subdivision: "",
    },
    {
      name: "Pramya Surapaneni",
      role: "Data Analyst",
      year: 2029,
      majors: "Electrical and Computer Engineering & Computer Science",
      linkedin: "https://www.linkedin.com/in/pramya-surapaneni",
      subdivision: "",
    },
  ],
  dku: [
    {
      name: "Abay Nygmetullin",
      role: "Analyst",
      year: 2029,
      majors: "",
      linkedin: "",
      subdivision: "",
    },
    {
      name: "Alston Leung",
      role: "Analyst",
      year: 2029,
      majors: "",
      linkedin: "",
      subdivision: "",
    },
    {
      name: "Amanda Gonzalez Mejia",
      role: "Co-Director",
      year: 2025,
      majors: "Political Economy and Public Policy",
      linkedin: "https://www.linkedin.com/in/amanda-niza-gonzalez-mej%C3%ADa",
      subdivision: "",
    },
    {
      name: "Arnur Janabekov",
      role: "Project Manager",
      year: 2029,
      majors: "",
      linkedin: "",
      subdivision: "",
    },
    {
      name: "Birkley Grunewald",
      role: "Project Manager",
      year: 2029,
      majors: "Quantitative Political Economy",
      linkedin: "https://www.linkedin.com/in/birkley-grunewald-a03186378",
      subdivision: "",
    },
    {
      name: "Bochao Zhang",
      role: "Advisor",
      year: 2026,
      majors: "",
      linkedin: "",
      subdivision: "",
    },
    {
      name: "Iliyas Yessenaly",
      role: "Analyst",
      year: 2028,
      majors: "Political Economy and economics",
      linkedin: "",
      subdivision: "",
    },
    {
      name: "Jennifer Li",
      role: "Analyst",
      year: 2029,
      majors: "Data Science",
      linkedin: "",
      subdivision: "",
    },
    {
      name: "Jiyuan Liu",
      role: "Analyst",
      year: 2028,
      majors: "Data Science",
      linkedin: "",
      subdivision: "",
    },
    {
      name: "Krishna Thiagarajan",
      role: "Co-Director",
      year: 2025,
      majors: "Philosophy",
      linkedin: "https://www.linkedin.com/in/krishna-thiagarajan",
      subdivision: "",
    },
    {
      name: "Lina Prado",
      role: "Analyst",
      year: 2029,
      majors: "",
      linkedin: "",
      subdivision: "",
    },
    {
      name: "Nicholas Preachuk",
      role: "Analyst",
      year: 2027,
      majors: "",
      linkedin: "",
      subdivision: "",
    },
    {
      name: "Ojas Paudyal",
      role: "Analyst",
      year: 2029,
      majors: "Quantitative Political Economy",
      linkedin: "",
      subdivision: "",
    },
    {
      name: "Roberto Adames",
      role: "Business Development",
      year: 2029,
      majors: "",
      linkedin: "",
      subdivision: "",
    },
    {
      name: "Sophia Paske",
      role: "Senior Analyst",
      year: 2028,
      majors: "",
      linkedin: "",
      subdivision: "",
    },
    {
      name: "Stacy Wang",
      role: "Analyst",
      year: 2029,
      majors: "",
      linkedin: "",
      subdivision: "",
    },
    {
      name: "Tomiris Bagdatjyzy",
      role: "Co-Director",
      year: 2025,
      majors: "Political Economy and Economics",
      linkedin: "https://www.linkedin.com/in/tomiris-bagdatkyzy",
      subdivision: "",
    },
    {
      name: "Youran Wang",
      role: "Analyst",
      year: 2028,
      majors: "",
      linkedin: "",
      subdivision: "",
    },
    {
      name: "Yuliya Kim",
      role: "Business Development",
      year: 2026,
      majors: "",
      linkedin: "",
      subdivision: "",
    },
    {
      name: "Zi Tong Chan",
      role: "Business Development",
      year: 2029,
      majors: "",
      linkedin: "",
      subdivision: "",
    },
    {
      name: "Ziyu Liu",
      role: "Senior Analyst",
      year: 2029,
      majors: "Quantitative Political Economic",
      linkedin: "",
      subdivision: "",
    },
    {
      name: "Nicholas Long",
      role: "Business Development",
      year: 2029,
      majors: "Undecided",
      linkedin: "",
      subdivision: "",
    },
    {
      name: "Ayusha Koirala",
      role: "Senior Analyst",
      year: 2026,
      majors: "Political Economy with track in Economics",
      linkedin: "",
      subdivision: "",
    },
    {
      name: "Lucia Liu",
      role: "Business Development",
      year: 2027,
      majors: "",
      linkedin: "",
      subdivision: "",
    },
    {
      name: "Yen Wen Choo",
      role: "Business Development",
      year: 2029,
      majors: "Undeclared",
      linkedin: "",
      subdivision: "",
    },
    {
      name: "Aris Rault",
      role: "Business Development",
      year: 2029,
      majors: "Applied Mathematics and computational sciences",
      linkedin: "",
      subdivision: "",
    },
  ],
  education: [
    {
      name: "Sophia Lynn",
      role: "Analyst",
      year: 2029,
      majors: "Economics",
      linkedin: "https://www.linkedin.com/in/sophia-lynn-2842b0383",
      subdivision: "",
    },
    {
      name: "Suhaib Mansour",
      role: "Co-Director",
      year: 2028,
      majors: "Mathematics",
      linkedin: "https://www.linkedin.com/in/suhaib-mansour-705117303",
      subdivision: "",
    },
    {
      name: "Evan Glasberg",
      role: "",
      year: 2028,
      majors: "Economics & Political Science",
      linkedin: "https://www.linkedin.com/in/evan-glasberg-b168952ab",
      subdivision: "",
    },
    {
      name: "Hardit Bhutani",
      role: "",
      year: 2029,
      majors: "Biology & Statistics",
      linkedin: "https://www.linkedin.com/in/hardit-bhutani",
      subdivision: "",
    },
    {
      name: "Owen Banks",
      role: "",
      year: 2029,
      majors: "Mathematics & Economics",
      linkedin: "https://www.linkedin.com/in/owen-banks-a0a03337a",
      subdivision: "",
    },
    {
      name: "Nikhilesh Kalyanaraman",
      role: "PM",
      year: 2029,
      majors: "Economics & Political Science",
      linkedin: "https://www.linkedin.com/in/nikhilesh-kalyanaraman-93057526a",
      subdivision: "",
    },
    {
      name: "Aarav Mehta",
      role: "",
      year: 2029,
      majors: "Economics",
      linkedin: "https://www.linkedin.com/in/aarav-mehta-30a613295",
      subdivision: "",
    },
    {
      name: "Brian Cha",
      role: "",
      year: 2029,
      majors: "Economics",
      linkedin: "https://www.linkedin.com/in/brian-cha-86454235a",
      subdivision: "",
    },
    {
      name: "Jimmy Helferty",
      role: "Co-Director",
      year: 2029,
      majors: "Economics",
      linkedin: "https://www.linkedin.com/in/jimmy-helferty-a709a6283",
      subdivision: "",
    },
    {
      name: "Aditi Hongalgi",
      role: "",
      year: 2029,
      majors: "Economics & Environmental Science and Policy",
      linkedin: "https://www.linkedin.com/in/aditi-hongalgi",
      subdivision: "",
    },
    {
      name: "Daud Malik",
      role: "",
      year: 2028,
      majors: "Chemistry & Public Policy",
      linkedin: "https://www.linkedin.com/in/daudmalik",
      subdivision: "",
    },
    {
      name: "Rajit Jain",
      role: "",
      year: 2027,
      majors: "Economics & Computer Science",
      linkedin: "https://www.linkedin.com/in/rajit-jain",
      subdivision: "",
    },
    {
      name: "Tony Liu",
      role: "",
      year: 2029,
      majors: "Economics & Public Policy",
      linkedin: "https://www.linkedin.com/in/tonyliu-duke",
      subdivision: "",
    },
    {
      name: "Avi Karamchandani",
      role: "",
      year: 2029,
      majors: "Mathematics & Economics",
      linkedin: "https://www.linkedin.com/in/avi-karamchandani",
      subdivision: "",
    },
    {
      name: "Nahom Theodros",
      role: "",
      year: 2028,
      majors: "Computer Science",
      linkedin: "https://www.linkedin.com/in/nahom-theodros",
      subdivision: "",
    },
    {
      name: "Andrew Noah Rodrigues Ferreira",
      role: "",
      year: 2029,
      majors: "Computer Science & Mathamatics",
      linkedin: "https://www.linkedin.com/in/andrew-rodrigues-ferreira",
      subdivision: "",
    },
    {
      name: "Carson Eisner",
      role: "",
      year: 2029,
      majors: "Economics & Mathamatics",
      linkedin: "https://www.linkedin.com/in/carsoneisner",
      subdivision: "",
    },
    {
      name: "Apollo Lee",
      role: "",
      year: 2029,
      majors: "Statstics and Mathamatics",
      linkedin: "https://www.linkedin.com/in/apollo-lee-1954ba348",
      subdivision: "",
    },
    {
      name: "Kabir Sankaran Rajendra",
      role: "",
      year: 2029,
      majors: "Mathamatics",
      linkedin: "https://www.linkedin.com/in/kabir-sankaranrajendra",
      subdivision: "",
    },
    {
      name: "Evan Lehmann",
      role: "",
      year: 2028,
      majors: "Economics & Education",
      linkedin: "https://www.linkedin.com/in/evan-lehmann-275797326",
      subdivision: "",
    },
  ],
  investment: [
    {
      name: "Cheyenne Tan",
      role: "Analyst",
      year: 2028,
      majors:
        "Biomedical Engineering & Innovation and Entrepreneurship & Computational Biology",
      linkedin: "https://www.linkedin.com/in/cheyenne-tan-sze-yi",
      subdivision: "Tech",
    },
    {
      name: "Dev Dwivedy",
      role: "Analyst",
      year: 2029,
      majors: "Computer Science & Economics",
      linkedin: "https://www.linkedin.com/in/dev-dwivedy-482b45263",
      subdivision: "Sports, Media, & Entertainment",
    },
    {
      name: "Jiaheng Yin",
      role: "Analyst",
      year: 2028,
      majors: "Economics & Public Policy",
      linkedin: "https://www.linkedin.com/in/jiaheng-yin-744473137",
      subdivision: "Industrials",
    },
    {
      name: "Kate Foster",
      role: "Analyst",
      year: 2029,
      majors: "Economics & Political Science",
      linkedin: "https://www.linkedin.com/in/katemfoster",
      subdivision: "Healthcare",
    },
    {
      name: "Devansh Roongta",
      role: "Analyst",
      year: 2029,
      majors: "Economics & Computer Science",
      linkedin: "https://www.linkedin.com/in/devanshroongta",
      subdivision: "Fintech",
    },
    {
      name: "Jay Patel",
      role: "Analyst",
      year: 2029,
      majors: "Economics & Computer Science",
      linkedin: "https://www.linkedin.com/in/jaypatel2029",
      subdivision: "Portfolio Management",
    },
    {
      name: "Daniel McNair",
      role: "Analyst",
      year: 2028,
      majors: "Economics",
      linkedin: "https://www.linkedin.com/in/daniel-mcnair-81b8b62b1",
      subdivision: "Industrials",
    },
    {
      name: "Maxwell Hyman",
      role: "Analyst",
      year: 2027,
      majors: "Economics & Statstics",
      linkedin: "https://www.linkedin.com/in/maxwell-hyman",
      subdivision: "Industrials",
    },
    {
      name: "Belle Phang",
      role: "Analyst",
      year: 2029,
      majors: "Mechanical Engineering & Energy Engineering",
      linkedin: "https://www.linkedin.com/in/belle-phang-8a7232261",
      subdivision: "Fintech",
    },
    {
      name: "Max Kelner",
      role: "Analyst",
      year: 2029,
      majors: "Economics",
      linkedin: "https://www.linkedin.com/in/max-kelner",
      subdivision: "Energy",
    },
    {
      name: "Aidan Shen",
      role: "Analyst",
      year: 2029,
      majors: "Mathamatics & Economics",
      linkedin: "https://www.linkedin.com/in/aidan-shen-305177218",
      subdivision: "Healthcare",
    },
    {
      name: "Story Kummer",
      role: "Analyst",
      year: 2029,
      majors: "Economics & Political Science",
      linkedin: "https://www.linkedin.com/in/storykummer",
      subdivision: "Consumer",
    },
    {
      name: "Advika Arya",
      role: "Analyst",
      year: 2029,
      majors: "Computer Science & Economics",
      linkedin: "https://www.linkedin.com/in/advika-arya-14abb1282",
      subdivision: "Tech",
    },
    {
      name: "Ashok Mittal",
      role: "Analyst",
      year: 2029,
      majors: "Economics & Mathamatics",
      linkedin: "https://www.linkedin.com/in/ashok-singh-mittal",
      subdivision: "Energy",
    },
    {
      name: "Alice  Karas",
      role: "Analyst",
      year: 2029,
      majors: "Undecided",
      linkedin: "https://www.linkedin.com/in/alice-karas-311b25315",
      subdivision: "Sports, Media, & Entertainment",
    },
    {
      name: "Isaac Lief",
      role: "Analyst",
      year: 2028,
      majors: "Computer Science & Statstics",
      linkedin: "https://www.linkedin.com/in/isaac-lief",
      subdivision: "Tech",
    },
    {
      name: "Paige LaForge",
      role: "Analyst",
      year: 2029,
      majors: "Economics",
      linkedin: "https://www.linkedin.com/in/paige-laforge-6a5624347",
      subdivision: "Energy",
    },
    {
      name: "Grace Ren",
      role: "Analyst",
      year: 2029,
      majors: "Economics & Latin",
      linkedin: "https://www.linkedin.com/in/graceren360",
      subdivision: "Sports, Media, & Entertainment",
    },
    {
      name: "Ethan Haas",
      role: "Analyst",
      year: 2029,
      majors: "Economics & English",
      linkedin: "https://www.linkedin.com/in/ethan-haas-336a82301",
      subdivision: "Fintech",
    },
    {
      name: "Ella Wang",
      role: "Analyst",
      year: 2029,
      majors: "Public Policy & Economics",
      linkedin: "https://www.linkedin.com/in/ella-wang-131964311",
      subdivision: "Consumer",
    },
    {
      name: "Jack Shaw",
      role: "PM",
      year: 2028,
      majors: "Data Science",
      linkedin: "https://www.linkedin.com/in/jackdshaw",
      subdivision: "Healthcare",
    },
    {
      name: "Hale Snyder",
      role: "PM",
      year: 2028,
      majors: "Economics & Energy and the Environment",
      linkedin: "https://www.linkedin.com/in/hale-snyder",
      subdivision: "Industrials",
    },
    {
      name: "Lawrence Gardner",
      role: "Analyst",
      year: 2029,
      majors: "Economics",
      linkedin: "https://www.linkedin.com/in/lawrence-samuel-gardner-5b0a77385",
      subdivision: "Sports, Media, & Entertainment",
    },
    {
      name: "Leyuan Zhou",
      role: "Analyst",
      year: 2029,
      majors: "Neuroscience & Economics",
      linkedin: "https://www.linkedin.com/in/leyuanzhou",
      subdivision: "Industrials",
    },
    {
      name: "Alex Wagonfeld",
      role: "PM",
      year: 2028,
      majors: "Economics & Energy and the Environment",
      linkedin: "https://www.linkedin.com/in/alexwagonfeld",
      subdivision: "Fintech",
    },
    {
      name: "Charlie Pausic",
      role: "PM",
      year: 2028,
      majors: "Economics",
      linkedin: "https://www.linkedin.com/in/charlie-pausic-214591250",
      subdivision: "Sports, Media, & Entertainment",
    },
    {
      name: "Matthew Roberts",
      role: "PM",
      year: 2028,
      majors: "Economics",
      linkedin: "https://www.linkedin.com/in/matthewlroberts1",
      subdivision: "Tech",
    },
    {
      name: "Andy Li",
      role: "PM",
      year: 2028,
      majors: "Economics & Computer Science",
      linkedin: "https://www.linkedin.com/in/andyli813",
      subdivision: "Portfolio Management",
    },
    {
      name: "Lilla Timperman",
      role: "PM",
      year: 2026,
      majors: "Political Science & Financial Economics",
      linkedin: "https://www.linkedin.com/in/lillatimperman",
      subdivision: "Portfolio Management",
    },
    {
      name: "Juhyun Nam",
      role: "Analyst",
      year: 2029,
      majors: "Economics & Computer Science",
      linkedin: "https://www.linkedin.com/in/juhyun-nam-4ba16b326",
      subdivision: "Portfolio Management",
    },
    {
      name: "Varenya Katta",
      role: "Analyst",
      year: 2029,
      majors: "Economics & Neuroscience",
      linkedin: "https://www.linkedin.com/in/varenyakatta",
      subdivision: "Healthcare",
    },
    {
      name: "Sajan Patel",
      role: "Analyst",
      year: 2029,
      majors: "Economics & Energy and the Environment",
      linkedin: "https://www.linkedin.com/in/sajan-patel-707o707",
      subdivision: "Consumer",
    },
    {
      name: "Asher Schenk",
      role: "Analyst",
      year: 2029,
      majors: "Economics",
      linkedin: "https://www.linkedin.com/in/asherschenk",
      subdivision: "Consumer",
    },
    {
      name: "Karim Wortelboer",
      role: "Analyst",
      year: 2028,
      majors: "Economics & Computer Science",
      linkedin: "https://www.linkedin.com/in/karimjwortelboer",
      subdivision: "Energy",
    },
    {
      name: "Eleana Yu",
      role: "PM",
      year: 2027,
      majors: "Economics & Markets and Management",
      linkedin: "https://www.linkedin.com/in/eleanayu",
      subdivision: "Consumer",
    },
    {
      name: "Pierce Satsky",
      role: "Analyst",
      year: 2028,
      majors: "Economics",
      linkedin: "https://www.linkedin.com/in/pierce-satsky-993995322",
      subdivision: "Consumer",
    },
    {
      name: "Mohith Gajjela",
      role: "Analyst",
      year: 2029,
      majors: "Economics & Computer Science",
      linkedin: "https://www.linkedin.com/in/mohith-gajjela",
      subdivision: "Tech",
    },
    {
      name: "Jeffrey Huang",
      role: "PM",
      year: 2027,
      majors: "Economics",
      linkedin: "https://www.linkedin.com/in/jeffrey-huang05",
      subdivision: "Energy",
    },
    {
      name: "Rashmi Thapa",
      role: "PM",
      year: 2028,
      majors: "Economics & Computer Science",
      linkedin: "https://www.linkedin.com/in/rashmii-thapaa",
      subdivision: "Tech",
    },
    {
      name: "Rendon Kuykendall",
      role: "Director",
      year: 2027,
      majors: "Public Policy & Economics",
      linkedin: "https://www.linkedin.com/in/rendon-kuykendall",
      subdivision: "",
    },
  ],
  partner: [
    {
      name: "Andy Li",
      role: "Partner",
      year: 2026,
      majors: "Economics & Computer Science",
      linkedin: "https://www.linkedin.com/in/andrew-li-duke",
      subdivision: "",
    },
    {
      name: "Sreya Gnanavel",
      role: "Partner",
      year: 2026,
      majors: "Statistics & Finance",
      linkedin: "https://www.linkedin.com/in/sreya-gnanavel",
      subdivision: "",
    },
    {
      name: "Danielle Park",
      role: "Partner",
      year: 2027,
      majors: "Public Policy & Computer Science",
      linkedin: "https://www.linkedin.com/in/daniellekimpark",
      subdivision: "",
    },
    {
      name: "Alayna Binder",
      role: "Partner",
      year: 2026,
      majors: "Statistics & Computer Science",
      linkedin: "https://www.linkedin.com/in/alaynabinder",
      subdivision: "",
    },
  ],
};

export const pastClients = {
  data: [
    {
      name: "Green-To-Go",
      logo: "green-to-go.png",
      description:
        "Green-To-Go is a subscription service providing reusable take-out containers. The team analyzed static data to provide insights such as check-out rates, membership growth, and restaurant performance.",
      deliverableLink:
        "https://docs.google.com/presentation/d/1_MR53GqPyIhjYog8lXC8Rdn-ABFoGDevyWuOD2inJYk/edit",
    },
    {
      name: "Junior Achievement",
      logo: "junior-achievement.png",
      description:
        "Junior Achievement is a nonprofit youth organization that works with local businesses, schools, and organizations to deliver experiential learning programs on work readiness, financial literacy, and entrepreneurship to young students.",
    },
    {
      name: "The Produce Box",
      logo: "the-produce-box.png",
      description:
        "The Produce Box is a subscription service that connects consumers to local farmers and artisans across North Carolina.",
      deliverableLink:
        "https://docs.google.com/presentation/d/1dwv74oWhiVXlcZR6VazV69khOvBz2PMQiL0TquTLO4U/edit",
    },
    {
      name: "Ginger",
      logo: "ginger.png",
      description:
        "Ginger (now Headspace) is a behavioral health monitoring platform that combines human care with data science and augmented intelligence to deliver on-demand mental healthcare.",
    },
  ],
  consulting: [
    {
      name: "Solar Unsoiled",
      logo: "solar-unsoiled.png",
      description:
        "Solar Unsoiled is an interactive, data-driven platform to optimize global solar energy production. Our team conducted market research on commercial-scale solar companies and identified market opportunities for these companies.",
    },
    {
      name: "Engage Globally",
      logo: "engage-globally.png",
      description:
        "Engage Globally supports community-led sustainable development in rural Northern Ghana. Our team identified potential small/medium business partners for the client to contact about potential financial support, researched regulatory process for nonprofits seeking to sell products in the U.S, and outlined a strategic business process map.",
    },
    {
      name: "Fillaree",
      logo: "fillaree.png",
      description:
        "Fillaree is a zero waste sustainable soap company. Our team defined a digital marketing strategy and conducted market outreach to better engage our client's audience.",
    },
    {
      name: "East Coast Greenway Alliance",
      logo: "east-coast-greenway-alliance.png",
      description:
        "The East Coast Greenway Alliance leads the development of the trail network. We completed a growth assessment of the organization and provided insights on compliance regulations for consideration.",
    },
  ],
};
